# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

sudo: false
language: cpp

git:
  submodules: false

# Define the matrix explicitly, manually expanding the combinations of (os, compiler, env).
# It is more tedious, but grants us far more flexibility.
matrix:
  include:
    # - os: linux
    #   compiler: gcc
    #   sudo: true
    #   install: ./scripts/install-linux-gcc.sh
    #   script: ./scripts/build-linux-autotools.sh
    #   env:
    #     - MATRIX_EVAL="CC=gcc && CXX=g++ && FC=gfortran"
    # - os: linux
    #   compiler: clang
    #   sudo: true
    #   install: ./scripts/install-linux-clang.sh
    #   script: ./scripts/build-linux-autotools.sh
    #   env:
    #     - MATRIX_EVAL="CC=clang && CXX=clang++ && FC=gfortran"
    - os: osx
      osx_image: xcode8
      compiler: gcc
      sudo: true
      install: ./scripts/install-osx-gcc.sh
      script: ./scripts/build-osx-autotools.sh
      env:
        - MATRIX_EVAL="brew update && CC=gcc && CXX=g++ && FC=gfortran"
    # - os: osx
    #   osx_image: xcode8
    #   compiler: gcc
    #   sudo: true
    #   install: ./scripts/install-osx-gcc6.sh
    #   script: ./scripts/build-osx-autotools.sh
    #   env:
    #     - MATRIX_EVAL="brew update && CC=gcc-6 && CXX=g++-6 && FC=gfortran-6"

before_install:
  # Create the keychain with a password
	- security create-keychain -p travis ios-build.keychain
	# Make the custom keychain default, so xcodebuild will use it for signing
	- security default-keychain -s ios-build.keychain
	# Unlock the keychain
	- security unlock-keychain -p travis ios-build.keychain
	# Add certificates to keychain and allow codesign to access them
	- security import ./Provisioning/certs/apple.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
	- security import ./Provisioning/certs/distribution.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
	- security import ./Provisioning/certs/distribution.p12 -k ~/Library/Keychains/ios-build.keychain -P $KEY_PASSWORD -T /usr/bin/codesign
	- security set-key-partition-list -S apple-tool:,apple: -s -k travis ios-build.keychain
  - eval "${MATRIX_EVAL}"
  - test -n $CC     && unset CC
  - test -n $CXX    && unset CXX
  - test -n $FC     && unset FC
  - test -n $F77    && unset F77


## These are the install and build (script) phases for the most common entries in the matrix.  They could be included
## in each entry in the matrix, but that is just repetitive.
install: make get-deps

before_script:
  - . ./scripts/env.sh
  - ./scripts/log-config.sh

# after_failure phase to dump the logs
after_failure:
  - cat ./tests/*.log

# For sudo=false builds this section installs the necessary dependencies.
addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - cmake
    - g++-5
    - clang-3.7

notifications:
  email: false
