# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

# List of whitelisted in travis packages for ubuntu-precise can be found here:
#   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
# List of whitelisted in travis apt-sources:
#   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json

sudo: false
language: cpp

git:
  submodules: false

# Define the matrix explicitly, manually expanding the combinations of (os, compiler, env).
# It is more tedious, but grants us far more flexibility.
matrix:
  include:
    # - os: linux
    #   compiler: gcc
    #   sudo: true
    #   install: ./scripts/install-linux-gcc.sh
    #   script: ./scripts/build-autotools.sh
    #   # This section installs the necessary dependencies.
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - cmake
    #         - gcc-5
    #         - g++-5
    #         - gfortran-5
    #         - libstdc++-5-dev
    #   env:
    #     - MATRIX_EVAL="sudo apt-get update && CC=gcc-5 && CXX=g++-5 && FC=gfortran-5"
    # - os: linux
    #   compiler: clang
    #   sudo: true
    #   install: travis_wait 120 ./scripts/install-linux-clang.sh
    #   # This section installs the necessary dependencies.
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-precise-3.8
    #       packages:
    #         - cmake
    #         - gcc-5
    #         - g++-5
    #         - gfortran-5
    #         - libstdc++-5-dev
    #         - clang-3.8
    #   env:
    #     - MATRIX_EVAL="sudo apt-get update && CC=clang-3.8 && CXX=clang++-3.8 && FC=gfortran-5"
    - os: osx
      osx_image: xcode10
      sudo: true
      install: travis_wait 120 ./scripts/install-osx.sh
      script: ./scripts/build-autotools.sh
      env:
        - MATRIX_EVAL="brew update && sudo rm -fr /usr/local/include/c++"
    # - os: osx
    #   osx_image: xcode8.3
    #   compiler: gcc
    #   sudo: true
    #   install: travis_wait 120 ./scripts/install-osx.sh
    #   env:
    #     - MATRIX_EVAL="brew update && sudo rm -fr /usr/local/include/c++ && CC=gcc-6 && CXX=g++-6 && FC=gfortran-6"

before_install:
  - test -n $CC   && unset CC
  - test -n $CXX  && unset CXX
  - test -n $FC   && unset FC
  - test -n $F77  && unset F77
  - eval "${MATRIX_EVAL}"

install: make get-deps

before_script:
  - . ./scripts/env.sh
  - ./scripts/log-config.sh

# After_failure phase to dump the logs
after_failure:
  - cat ./tests/*.log

notifications:
  email: false
