# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

sudo: false
language: cpp

git:
  submodules: false

before_install:
  - test -n $CC     && unset CC
  - test -n $CXX    && unset CXX
  - test -n $FC     && unset FC
  - test -n $F77    && unset F77

# Define the matrix explicitly, manually expanding the combinations of (os, compiler, env).
# It is more tedious, but grants us far more flexibility.
matrix:
  include:
    # - os: linux
    #   compiler: gcc
    #   sudo: true
    #   install: ./scripts/install-linux.sh && ./scripts/log-config.sh
    #   script: ./scripts/build-linux-autotools.sh
    # - os: linux
    #   compiler: clang
    #   sudo: true
    #   install: ./scripts/install-linux.sh && ./scripts/log-config.sh
    #   script: ./scripts/build-linux-autotools.sh
    - os: osx
      osx_image: xcode8
      compiler: gcc
      sudo: true
      install: ./scripts/install-osx.sh && ./scripts/log-config.sh
      script: ./scripts/build-osx-autotools.sh
    - os: osx
      osx_image: xcode7
      compiler: gcc
      sudo: true
      install: ./scripts/install-osx.sh && ./scripts/log-config.sh
      script: ./scripts/build-osx-autotools.sh
## These are the install and build (script) phases for the most common entries in the matrix.  They could be included
## in each entry in the matrix, but that is just repetitive.
install: make get-deps
  - ./scripts/install-${TRAVIS_OS_NAME}.sh
  - . ./scripts/env-${TRAVIS_OS_NAME}.sh
  - ./scripts/log-config.sh

# after_failure phase to dump the logs
after_failure:
  - cat ./tests/*.log

# For sudo=false builds this section installs the necessary dependencies.
addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - cmake
    - g++-5
    - clang-3.7

env:
  - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && FC=gfortran-5"

notifications:
  email: false
